### ISSUE TITLE
Recompute failed after changing size

### ISSUE THREAD

**Issue by AussieBrad** [Stu142/Freecad-dimension-variable-editing#2]
Freecad version 0.20.2 fresh install on windows 11

Downloaded **FreeCAD Gridfinity Parametric Simple Storage Bin.FCStd** and **FreeCAD Gridfinity Parametric Bin V2.FCStd**

Changed **x_grid_units** to **1** and **y_grid_units** to **4**

Upon recompute I receive the error

14:46:28  No extension found of type 'PartGui::ViewProviderGridExtension'
14:52:03  Recompute failed! Please check report view.

**Comment by Stu142** [comment]
Thanks for reporting this. I have identified and fixed the problem sketch on both ard replaced the uploaded models with the new version. 

Please let me know if you encounter any other errors.

**Comment by AussieBrad** [comment]
It is still not working for me.

Report window show the following on loading FreeCAD Gridfinity Parametric Simple Storage Bin.FCStd, downloaded from Printables which showed the file date as today, so it was the updated file.

19:20:16  No extension found of type 'PartGui::ViewProviderGridExtension'
19:20:40  Recompute failed! Please check report view.

**Comment by Stu142** [comment]
I should have caught it right away, but I created the file on FreeCAD version 21.1, which is what seems to be causing the problem. 

I tried opening it with FreeCAD 20.2 and got the same error you did. A quick Google didn't present any solutions so updating may be the only way. 

I will add a note to the printables page about the FreeCAD version requirement.
